### ISSUE TITLE
Error: no tickets left to pull from. And git setup question.

### ISSUE THREAD

**Issue by ms8277** [mrf345/FQM#13]
Greeting Mohamed, I hope everything is well with you. We're having an issue with the Queue Management System, where for some tasks when the operator tries to pull the next ticket he/she gets the message that says " Error: no tickets left to pull from" We had a similar issue in the past, and you've guided me through certain steps to fix the issue, which involved using SQLlight plugin to change some values in the database. Unfortunately, I forgot those steps. Can you please help with this? Any way to prevent this error from happening in the first place?

Thanks

**Comment by mrf345** [comment]
Hello @ms8277 , sorry for the late replay. And thanks for the well detailed issue, which i've finally got enough free time to reproduce. I'm about to merge a PR https://github.com/mrf345/FQM/pull/32 that will hopefully resolve it once and for all 🎉

**Comment by ms8277** [comment]
Thank you very much. That's great news!
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by ms8277** [comment]
Now, we just need to pull the latest version of the system to apply the fixes?

**Comment by mrf345** [comment]
Yes pulling the latest commit and then from within the system pulling a
ticket should get rid of the sticking ticket.

**Comment by ms8277** [comment]
Hi Mohammed, last time I did the installation, I did it through
downloading the source code directly from your GitHub site. I didn't use
Git at that time. Is possible for me to download specific files using the
normal download/overwrite way to get the new updated beta version, Or I
should do full installation using git?

Thanks.
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by mrf345** [comment]
It should be fine to overwrite files, but I've not test to confirm out of experience. Personally i would prefer to copy the `data.sqlite` and the `multimedia` folder to the new project source code instead, so you won't lose your current setup and data.

If you went with overwriting be-careful of overwriting your `data.sqlite` that's basically the database file.

**Comment by ms8277** [comment]
Thank you very much, Mohammed, for your support. I've managed to do a fresh
installation using Git. It's better for the future management of the
project. I'm currently getting just one issue, which is if ran the
*run.py *with
*python3.7 *I get the error *"ImportError: cannot import name 'Dummy' from
'escpos.printer'
(/usr/local/lib/python3.7/dist-packages/escpos/printer.py)"*  While it
works fine with *python3.6* it might not look like a big deal, as long it
works, but yet I'm trying to make it work with *python3.7 *(the default
python for my system).
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by ms8277** [comment]
Another thing, when do this *sudo python3.6 run.py --ip 192.168.2.1 --port
3000*  it still uses the default IP and port (127.0.0.1 and port 5000)

Thanks.
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by mrf345** [comment]
Hi @ms8277 ,

The first issue i guess is the result of using an incompatible package `python-escpos` not sure how has that happened. Are you using an isolated virtual environment with Python 3.7 ?

If not, try to use one it will help you avoid similar issues in the future:
1. `pip install virtualenv`
2. `virtualenv --python=python3.7 installation'
3.`'installation\Scripts\activate.bat`
4. `pip install requirements\main.txt`
5. `python run.py --cli --ip 192.168.2.1 --port 3000`

If you notice the `--cli` flag is used to enable the command-line interface. If the flag `--cli` is not passed we'll ignore the reset of the arguments and lunch the GUI instead.

**Comment by ms8277** [comment]
I did install the environment but didn't use it. Is this is the right
command: *virtualenv --python=python3.7 installation'
3.'installation\Scripts\activate.bat` *it doesn't seem to work. Is there
any mistake in the quotes or the dashes in *
'installation\Scripts\activate.bat`?*
Yesterday I was doing the tests on a test server, today, when I tried to
apply the changes on the actual server both python 3.6 and 3.7, are given
the same error.
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by ms8277** [comment]
Hi Mohammed
I managed to make the virtualenv work. Now the system works fine.
Probably it was a conflict between the different version of Pythons I have.

Many thanks for your help.
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by mrf345** [comment]
My pleasure, happy it has worked out.

**Comment by ms8277** [comment]
Hi Mohammed
The problem is happening again! (even if I try to completely delete the
office/ticket or user and recreate everything again, the problem continue)
We're now in the peak time and it's not working.
[image: queue-issue.png]
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by ms8277** [comment]
Please note that more than one user is using the same username to login to
a specific service, do you think that might because the issue?
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by ms8277** [comment]
Almost all of the offices are not working now
[image: Screenshot_012620_112315_AM.jpg]
----
Mohammad K. Yaseen
Director of E-Learning
Website <http://mohammadsite.com> | Blog <http://mohammadblog.com> |
LinkedIn <http://om.linkedin.com/in/mohammad82>

**Comment by mrf345** [comment]
Hello @ms8277 

Unfortunately i'm no longer able to reproduce the issue locally. Not sure if multiple users is what's causing it, Nonetheless it's a high probability. I was planning to add a an integration test-case to cover generating and pulling tickets with multiple users in this upcoming release.

However until then, let's try to figure out what have went wrong. did the system generate `errors.log` file ? if so could you please attach its content here. And if you don't mind sending me the `data.sqlite` database file that will help greatly in debugging it.

Feel free to reach me through  [email](mailto:mrf345@gmail.com), hopefully i will have the time to help you get it back up.

**Comment by mrf345** [comment]
Hello @ms8277 

I was able to reproduce the issue while testing with the database file you've kindly sent me. I'm about to merge a PR https://github.com/mrf345/FQM/pull/55  that will hopefully resolve the issue.

I've retested manually and the issue seems to be no longer reproducible. Please give it a shot and let me know if the issue still persists.

![testing_last_ticekt_stuck](https://user-images.githubusercontent.com/26286907/73348408-68457280-429a-11ea-9e68-c97c217dc4d3.gif)
