### ISSUE TITLE
run.py fails to run after upgrade to 0.9

### ISSUE THREAD

**Issue by skymaker-c2is** [mrf345/FQM#228]
I've just updated (via git fetch) to the latest version. Unfortunately, the following error occurs:

> $ python3 run.py --cli --port 8080 --ip 0.0.0.0
> Traceback (most recent call last):
>   File "run.py", line 1, in <module>
>     from app.cli import interface
>   File "/home/pi/FQM/app/__init__.py", line 2, in <module>
>     from app.main import bundle_app # noqa
>   File "/home/pi/FQM/app/main.py", line 16, in <module>
>     from app.middleware import db, login_manager, files, gtranslator, gTTs, migrate
>   File "/home/pi/FQM/app/middleware.py", line 19, in <module>
>     gTTs = gtts(route=True, failsafe=True, logging=False)
>   File "/home/pi/.local/lib/python3.7/site-packages/static_parameters/__init__.py", line 63, in wrapper
>     return function(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'failsafe'

I then cloned the repo again to test it, and it throws the same error. Any idea how to solve that?

**Comment by skymaker-c2is** [comment]
I'm closing this, since it was my mistake: You should always have a look which python version you use currently... :)

**Comment by mrf345** [comment]
And always make sure your packages are up to date `pip install -r requirements/deploy.txt` 😉
